# Generated by Django 3.0.6 on 2020-06-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200608_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('T', 'Turkce'), ('S', 'Sosyal'), ('M', 'Matematik'), ('F', 'Fen'), ('Q', 'Default')], default='Q', max_length=50),
        ),
    ]
