# Generated by Django 3.0.6 on 2020-06-03 03:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('section', models.CharField(max_length=1)),
                ('advisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Teacher')),
            ],
        ),
    ]
