# Generated by Django 3.0.6 on 2020-06-04 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20200603_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'ordering': ['-result']},
        ),
        migrations.AddField(
            model_name='exam',
            name='klass',
            field=models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(8)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='sheet',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
