# Generated by Django 3.0.6 on 2020-06-05 20:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student'),
        ('exams', '0006_auto_20200604_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='answers',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='sheet',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', '.pdf', '.txt', 'txt', '.docx', 'docx'])]),
        ),
        migrations.CreateModel(
            name='ExamAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=255)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exams.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
        ),
    ]
