# Generated by Django 3.0.6 on 2020-06-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student'),
        ('exams', '0007_auto_20200605_2346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examanswers',
            unique_together={('exam', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'student')},
        ),
    ]
