# Generated by Django 3.0.6 on 2020-06-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student'),
        ('exams', '0008_auto_20200605_2352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamAnswers',
            new_name='ExamStudentAnswer',
        ),
    ]
