# Generated by Django 3.0.6 on 2020-06-05 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student'),
        ('exams', '0009_auto_20200605_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='examstudentanswer',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exams.Exam'),
        ),
        migrations.AlterField(
            model_name='examstudentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to='users.Student'),
        ),
    ]
