# Generated by Django 3.0.6 on 2020-06-05 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20200606_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 0, 48, 4, 917180)),
        ),
    ]
