# Generated by Django 3.0.6 on 2020-06-06 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_auto_20200606_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'ordering': ['-exam']},
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 10, 36, 50, 382970)),
        ),
    ]
