# Generated by Django 3.0.6 on 2020-06-08 01:22

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_auto_20200606_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='QSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('solution', models.ImageField(upload_to='solutions')),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 4, 22, 33, 976072)),
        ),
        migrations.CreateModel(
            name='ExamSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='exams.Exam')),
                ('solutions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.QSolution')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributed_solutions', to='exams.Exam')),
            ],
        ),
    ]
