# Generated by Django 3.0.6 on 2020-06-08 02:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_auto_20200608_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 5, 58, 20, 60459)),
        ),
        migrations.AlterField(
            model_name='examsolution',
            name='solutions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.QSolution'),
        ),
    ]
