# Generated by Django 3.0.6 on 2020-06-08 03:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_auto_20200608_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 6, 8, 42, 72634)),
        ),
        migrations.AlterField(
            model_name='examsolution',
            name='solutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.QSolution'),
        ),
        migrations.AlterUniqueTogether(
            name='examsolution',
            unique_together={('subject', 'solutions')},
        ),
    ]
